---
- name: Ensure systems are CIS compliant
  hosts: all
  become: yes
  roles:
    - role: rhel7-cis
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'
