- name: CIS.1.1.1 | PASSWORD | Set password history to {{ win2012_harden_password_history }} passwords remembered
  win_secedit:
    category: System Access
    key: PasswordHistorySize
    value: "{{ win2012_harden_password_history }}"
  when: cis_1_1_1
  tags:
    - CIS.1.1.1

- name: CIS.1.1.2 | PASSWORD | Set minimum password age to {{ win2012_harden_min_password_age }}
  win_secedit:
    category: System Access
    key: MinimumPasswordAge
    value: "{{ win2012_harden_min_password_age }}"
  when: cis_1_1_2
  tags:
    - CIS.1.1.2

- name: CIS.1.1.3 | PASSWORD | Set maximum password age to {{ win2012_harden_max_password_age }} days
  win_secedit:
    category: System Access
    key: MaximumPasswordAge
    value: "{{ win2012_harden_max_password_age }}"
  when: cis_1_1_3
  tags:
      - CIS.1.1.3

- name: CIS.1.1.4 | PASSWORD | Set minimum password length to {{ win2012_harden_min_password_length }}
  win_secedit:
    category: System Access
    key: MinimumPasswordLength
    value: "{{ win2012_harden_min_password_length }}"
  when: cis_1_1_4
  tags:
    - CIS.1.1.4

- name: CIS.1.1.5 | PASSWORD | Do not store passwords using reversible encryption
  win_secedit:
    category: System Access
    key: ClearTextPassword
    value: "{{ win2012_harden_clear_text_password | int }}"
  when: cis_1_1_5
  tags:
    - CIS.1.1.5

- name: CIS.1.1.6 | PASSWORD | Set account lockout count to {{ win2012_harden_account_lockout_count }}
  win_secedit:
    category: System Access
    key: LockoutBadCount
    value: "{{ win2012_harden_account_lockout_count }}"
  when: cis_1_1_6
  tags:
    - CIS.1.1.6

- name: CIS.1.1.7 | PASSWORD | Set account lockout duration to {{ win2012_harden_account_lockout_duration }}
  win_secedit:
    category: System Access
    key: LockoutDuration
    value: "{{ win2012_harden_account_lockout_duration }}"
  when: cis_1_1_7
  tags:
    - CIS.1.1.7

- name: CIS.1.1.8 | PASSWORD | Set reset account lockout counter to {{ win2012_harden_account_lockout_reset }}
  win_secedit:
    category: System Access
    key: ResetLockoutCount
    value: "{{ win2012_harden_account_lockout_reset }}"
  when: cis_1_1_8
  tags:
    - CIS.1.1.8

- name: CIS.1.1.9.2, CIS.1.1.9.4 | PASSWORD | Ensure account password never expires
  win_user:
    name: Replicate
    password_never_expires: yes
  when:
    - cis_1_1_9_2 or cis_1_1_9_4
    - "item in win_users"
  with_items: "{{ win2012_harden_password_never_expires_accounts }}"
  tags:
    - CIS.1.1.9.2
    - CIS.1.1.9.4

